name: parallel
channels:
  - defaults
dependencies:
  - python =3.5
  - bokeh
  - dask
  - distributed
  - ipyparallel
  - joblib
  - jupyter
  - matplotlib
  - pandas =0.19
  - pandas-datareader
  - pytables
  - scikit-learn
  - snakeviz
  - ujson

